### ISSUE TITLE
Question: Using an image from project folder

### ISSUE THREAD

**Issue by morlzor** [pascoual/meteor-pdfkit#14]
Sorry for the newbie question, but I've been going around with this for a while.

I have an image in my public folder, which i want to use as a header in the pdf. 
From the Quick Start example, i can see you use a image that is on the db. Is that necessary?

How do I use an image from my projects directory?

If i just use doc.image(imagePath), i get an error saying that that file/dir doesn't exist.

Thanks

**Comment by pascoual** [comment]
Even if you use full path (/home/you/...) ?

**Comment by morlzor** [comment]
Sorry for not saying anything. Forgot about this.

I ended up solving it like this:

**Comment by mrn3** [comment]
Thanks so much on this!  I was banging my head on the wall trying to figure this out, and your solution worked perfectly (using the process.env.PWD command)!
