### ISSUE TITLE
pdfkit ignores margin setting

### ISSUE THREAD

**Issue by soitech** [pascoual/meteor-pdfkit#16]
creating a new document:
    doc = new PDFDocument({size:'Letter', margin: 36});
Does not seem to actually set any margins. Text will start at the left edge of the page and run to the right edge of the page. All elements essentially have to be manually positioned. I've also tried setting the margins in separate addPage() calls, with similar lack of effect. 
Not a huge problem, just a bit of a hassle and a documented feature that doesn't seem to be working in current meteor versions.

**Comment by pascoual** [comment]
This package will stick to 0.4.3.
A new package with PDFKit 0.7.1 will come.

Closing...
